# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17rv7cBEaPZ9gi5-K9SI_aTBvazL6hBjw
"""

import math
import joblib
import pandas as pd
import streamlit as st
from pathlib import Path

# Configuração da página

st.set_page_config(
    page_title="Predição de Risco de Defasagem",
    page_icon="🎓",
    layout="wide"
)

# Carregar modelo

@st.cache_resource
def carregar_modelo():
    BASE_DIR = Path(__file__).resolve().parent
    MODEL_PATH = BASE_DIR.parent / "models" / "model.joblib"
    return joblib.load(MODEL_PATH)

modelo = carregar_modelo()

# Ordem exata esperada pelo pipeline
FEATURES_MODELO = [
    "idade",
    "ano",
    "ano_ingresso",
    "tempo_programa",
    "num_avaliacoes",
    "num_notas_disponiveis",
    "media_notas_disponiveis",
    "ian",
    "iaa",
    "ieg",
    "ips",
    "ida",
    "ipv",
    "inde",
    "defasagem",
    "score_risco_eda",
    "ida_prev",
    "ieg_prev",
    "ipv_prev",
    "ips_prev",
    "iaa_prev",
    "ian_prev",
    "inde_prev",
    "defasagem_prev",
    "delta_ida",
    "delta_ieg",
    "delta_ipv",
    "delta_inde",
    "pedra",
    "pedra_ordem",
    "instituicao_ensino",
    "genero",
    "flag_iaa_missing",
    "flag_inde_missing",
    "flag_ida_missing",
    "flag_ipv_missing",
    "flag_ieg_missing",
    "flag_pedra_missing",
]

MAP_PEDRA = {
    "Quartzo": 1,
    "Ágata": 2,
    "Ametista": 3,
    "Topázio": 4,
}

OPCOES_INSTITUICAO = [
    "Escola Pública",
    "Pública",
    "Privada",
    "Privada - Programa de Apadrinhamento",
    "Privada - Pagamento por Empresa Parceira",
    "Privada - Parcerias com Bolsa 100%",
    "Bolsista Universitário - Formado(a)",
    "Concluiu o 3º EM",
    "Universitário",
    "Outros",
]

OPCOES_GENERO = ["Feminino", "Masculino"]

# Funções auxiliares

def para_float_ou_nan(valor: str):
    texto = str(valor).strip().replace(",", ".")
    if texto == "":
        return math.nan
    try:
        return float(texto)
    except ValueError:
        return math.nan


def faixa_risco(prob: float) -> str:
    if prob <= 0.25:
        return "Baixo"
    if prob <= 0.50:
        return "Moderado"
    if prob <= 0.75:
        return "Alto"
    return "Crítico"


def cor_faixa(faixa: str) -> str:
    return {
        "Baixo": "#2e7d32",
        "Moderado": "#f9a825",
        "Alto": "#ef6c00",
        "Crítico": "#c62828",
    }.get(faixa, "#1565c0")


def montar_dataframe_entrada(
    idade: int,
    ano: int,
    ano_ingresso: int,
    num_avaliacoes: int,
    num_notas_disponiveis: int,
    media_notas_disponiveis: float,
    ian: float,
    iaa: float,
    ieg: float,
    ips: float,
    ida: float,
    ipv: float,
    inde: float,
    defasagem: float,
    ida_prev: float,
    ieg_prev: float,
    ipv_prev: float,
    ips_prev: float,
    iaa_prev: float,
    ian_prev: float,
    inde_prev: float,
    defasagem_prev: float,
    pedra: str,
    instituicao_ensino: str,
    genero: str,
) -> pd.DataFrame:
    tempo_programa = ano - ano_ingresso
    pedra_ordem = MAP_PEDRA.get(pedra, math.nan)

    delta_ida = ida - ida_prev if not (pd.isna(ida) or pd.isna(ida_prev)) else math.nan
    delta_ieg = ieg - ieg_prev if not (pd.isna(ieg) or pd.isna(ieg_prev)) else math.nan
    delta_ipv = ipv - ipv_prev if not (pd.isna(ipv) or pd.isna(ipv_prev)) else math.nan
    delta_inde = inde - inde_prev if not (pd.isna(inde) or pd.isna(inde_prev)) else math.nan

    score_risco_eda = int((not pd.isna(ida)) and ida < 6) + int((not pd.isna(ipv)) and ipv < 7)

    flag_iaa_missing = int(pd.isna(iaa))
    flag_inde_missing = int(pd.isna(inde))
    flag_ida_missing = int(pd.isna(ida))
    flag_ipv_missing = int(pd.isna(ipv))
    flag_ieg_missing = int(pd.isna(ieg))
    flag_pedra_missing = int(pd.isna(pedra_ordem))

    linha = {
        "idade": idade,
        "ano": ano,
        "ano_ingresso": ano_ingresso,
        "tempo_programa": tempo_programa,
        "num_avaliacoes": num_avaliacoes,
        "num_notas_disponiveis": num_notas_disponiveis,
        "media_notas_disponiveis": media_notas_disponiveis,
        "ian": ian,
        "iaa": iaa,
        "ieg": ieg,
        "ips": ips,
        "ida": ida,
        "ipv": ipv,
        "inde": inde,
        "defasagem": defasagem,
        "score_risco_eda": score_risco_eda,
        "ida_prev": ida_prev,
        "ieg_prev": ieg_prev,
        "ipv_prev": ipv_prev,
        "ips_prev": ips_prev,
        "iaa_prev": iaa_prev,
        "ian_prev": ian_prev,
        "inde_prev": inde_prev,
        "defasagem_prev": defasagem_prev,
        "delta_ida": delta_ida,
        "delta_ieg": delta_ieg,
        "delta_ipv": delta_ipv,
        "delta_inde": delta_inde,
        "pedra": pedra,
        "pedra_ordem": pedra_ordem,
        "instituicao_ensino": instituicao_ensino,
        "genero": genero,
        "flag_iaa_missing": flag_iaa_missing,
        "flag_inde_missing": flag_inde_missing,
        "flag_ida_missing": flag_ida_missing,
        "flag_ipv_missing": flag_ipv_missing,
        "flag_ieg_missing": flag_ieg_missing,
        "flag_pedra_missing": flag_pedra_missing,
    }

    df_entrada = pd.DataFrame([linha])
    return df_entrada[FEATURES_MODELO]

# Estilo

st.markdown(
    """
    <style>
    .stButton > button {
        background-color: #1565c0;
        color: white;
        font-weight: 700;
        border-radius: 10px;
        border: none;
        padding: 0.7rem 1.2rem;
    }
    .stButton > button:hover {
        background-color: #0d47a1;
        color: white;
    }
    .box-resultado {
        padding: 1rem 1.2rem;
        border-radius: 12px;
        color: white;
        font-weight: 600;
        margin-top: 1rem;
    }
    </style>
    """,
    unsafe_allow_html=True
)

# Título

st.title("🎓 Predição de Risco de Defasagem")
st.markdown(
    """
    Preencha os dados do aluno para estimar a **probabilidade de risco de defasagem** no próximo período.
    As variáveis derivadas, como `tempo_programa`, `score_risco_eda` e `deltas`, são calculadas automaticamente.
    """
)

with st.expander("Ver variáveis usadas pelo modelo"):
    st.write(FEATURES_MODELO)

# Formulário

with st.form("form_predicao"):
    st.subheader("1) Perfil do aluno")
    c1, c2, c3 = st.columns(3)

    with c1:
        idade = st.number_input("Idade", min_value=5, max_value=40, value=14, step=1)
        ano = st.number_input("Ano da avaliação", min_value=2022, max_value=2030, value=2024, step=1)
    with c2:
        ano_ingresso = st.number_input("Ano de ingresso", min_value=2015, max_value=2030, value=2022, step=1)
        genero = st.selectbox("Gênero", OPCOES_GENERO)
    with c3:
        pedra = st.selectbox("Pedra", list(MAP_PEDRA.keys()))
        instituicao_ensino = st.selectbox("Instituição de ensino", OPCOES_INSTITUICAO)

    st.subheader("2) Indicadores atuais")
    c4, c5, c6 = st.columns(3)

    with c4:
        ian = st.number_input("IAN atual", min_value=-10.0, max_value=10.0, value=5.0, step=0.1)
        iaa_txt = st.text_input("IAA atual (deixe em branco se ausente)", value="7.0")
        ieg_txt = st.text_input("IEG atual (deixe em branco se ausente)", value="8.0")
    with c5:
        ips_txt = st.text_input("IPS atual (deixe em branco se ausente)", value="6.0")
        ida_txt = st.text_input("IDA atual (deixe em branco se ausente)", value="6.5")
        ipv_txt = st.text_input("IPV atual (deixe em branco se ausente)", value="7.0")
    with c6:
        inde_txt = st.text_input("INDE atual (deixe em branco se ausente)", value="7.0")
        defasagem = st.number_input("Defasagem atual", min_value=-10.0, max_value=10.0, value=-1.0, step=1.0)
        num_avaliacoes = st.number_input("Número de avaliações", min_value=0, max_value=20, value=4, step=1)

    c7, c8 = st.columns(2)
    with c7:
        num_notas_disponiveis = st.number_input("Número de notas disponíveis", min_value=0, max_value=10, value=3, step=1)
    with c8:
        media_notas_disponiveis_txt = st.text_input("Média das notas disponíveis", value="6.8")

    st.subheader("3) Histórico do período anterior")
    c9, c10, c11, c12 = st.columns(4)

    with c9:
        ida_prev_txt = st.text_input("IDA anterior", value="6.0")
        ieg_prev_txt = st.text_input("IEG anterior", value="7.5")
    with c10:
        ipv_prev_txt = st.text_input("IPV anterior", value="6.8")
        ips_prev_txt = st.text_input("IPS anterior", value="5.8")
    with c11:
        iaa_prev_txt = st.text_input("IAA anterior", value="6.5")
        ian_prev = st.number_input("IAN anterior", min_value=-10.0, max_value=10.0, value=5.0, step=0.1)
    with c12:
        inde_prev_txt = st.text_input("INDE anterior", value="6.7")
        defasagem_prev = st.number_input("Defasagem anterior", min_value=-10.0, max_value=10.0, value=-1.0, step=1.0)

    botao = st.form_submit_button("🔍 Prever risco de defasagem", type="primary")

# Predição

if botao:
    iaa = para_float_ou_nan(iaa_txt)
    ieg = para_float_ou_nan(ieg_txt)
    ips = para_float_ou_nan(ips_txt)
    ida = para_float_ou_nan(ida_txt)
    ipv = para_float_ou_nan(ipv_txt)
    inde = para_float_ou_nan(inde_txt)
    media_notas_disponiveis = para_float_ou_nan(media_notas_disponiveis_txt)

    ida_prev = para_float_ou_nan(ida_prev_txt)
    ieg_prev = para_float_ou_nan(ieg_prev_txt)
    ipv_prev = para_float_ou_nan(ipv_prev_txt)
    ips_prev = para_float_ou_nan(ips_prev_txt)
    iaa_prev = para_float_ou_nan(iaa_prev_txt)
    inde_prev = para_float_ou_nan(inde_prev_txt)

    try:
        df_entrada = montar_dataframe_entrada(
            idade=idade,
            ano=ano,
            ano_ingresso=ano_ingresso,
            num_avaliacoes=num_avaliacoes,
            num_notas_disponiveis=num_notas_disponiveis,
            media_notas_disponiveis=media_notas_disponiveis,
            ian=ian,
            iaa=iaa,
            ieg=ieg,
            ips=ips,
            ida=ida,
            ipv=ipv,
            inde=inde,
            defasagem=defasagem,
            ida_prev=ida_prev,
            ieg_prev=ieg_prev,
            ipv_prev=ipv_prev,
            ips_prev=ips_prev,
            iaa_prev=iaa_prev,
            ian_prev=ian_prev,
            inde_prev=inde_prev,
            defasagem_prev=defasagem_prev,
            pedra=pedra,
            instituicao_ensino=instituicao_ensino,
            genero=genero,
        )

        prob_risco = float(modelo.predict_proba(df_entrada)[0, 1])
        classe = int(prob_risco >= 0.5)
        faixa = faixa_risco(prob_risco)
        cor = cor_faixa(faixa)

        st.subheader("Resultado da predição")
        st.markdown(
            f"""
            <div class="box-resultado" style="background-color:{cor};">
                Probabilidade de risco: {prob_risco:.1%}<br>
                Classificação: {faixa}<br>
                Predição binária do modelo (threshold 0.5): {"Em risco" if classe == 1 else "Sem risco"}
            </div>
            """,
            unsafe_allow_html=True
        )

        if faixa == "Baixo":
            st.success("O aluno apresenta baixa probabilidade de entrar em situação de risco de defasagem no próximo período.")
        elif faixa == "Moderado":
            st.warning("O aluno apresenta sinais moderados de risco. Recomenda-se acompanhamento.")
        elif faixa == "Alto":
            st.warning("O aluno apresenta alta probabilidade de risco. Vale priorizar atenção pedagógica.")
        else:
            st.error("O aluno apresenta risco crítico de defasagem. Recomenda-se intervenção preventiva prioritária.")

        with st.expander("Ver dados enviados ao modelo"):
          st.dataframe(df_entrada)

    except Exception as e:
        st.error("Não foi possível gerar a predição.")
        st.exception(e)